### ISSUE TITLE
Conda: ImportError when importing pyvinecopulib in Python 3.7

### ISSUE THREAD

**Issue by dmey** [vinecopulib/pyvinecopulib#58]
The following error is raised when trying to import pyvinecopulib in Python 3.7 on anaconda:

```
>>> import pyvinecopulib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

### How to reproduce
Create file named `environment.yml` with the following content:

``` yml
name: pyvinecopulib-py37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - setuptools
  - pybind11
  - pip:
    - pyvinecopulib
```

Then create the environment with `conda env create -f environment.yml` and activate with `conda activate pyvinecopulib-py37` from your Anaconda Prompt. Then launch `python` and `import pyvinecopulib`.
